[' 2    THE NEW YORK DECLARATION FAQs  The New York Declaration for Refugees and Migrants 1.',
 'What is it?',
 'On 19 September 2016, the United Nations General Assembly hosted a high-level Summit for Refugees and Migrants that aimed at improving the way in which the international community responds to large movements of refugees and migrants.',
 'At the Summit, all 193 Member States of the United Nations unanimously adopted the New York Declaration for Refugees and Migrants (Resolution 71/1).',
 'As the name suggests, the New York Declaration for Refugees and Migrants addresses the situations faced by refugees and by migrants.',
 'There are robust commitments that apply equally to refugees and migrants (on topics including racism, xenophobia and human trafficking), as well as separate commitments for refugees and for migrants.',
 'Furthermore, the New York Declaration lays the groundwork for further action to improve the situation of refugees and migrants by laying out a and regular migration, which are to be adopted in late 2018.',
 'States have also pledged to consider the development of non-binding guiding principles for migrants in vulnerable situations.',
 'For further information, visit: www.unhcr.org/newyorkdeclaration .',
 '2.',
 'Why is it important for refugees?',
 'The New York Declaration is a milestone for global solidarity and refugee protection at this time of unprecedented displacement.',
 'The set of commitments, agreed by Member States, reflects an understanding that protecting those who are forced to flee, and supporting the countries that shelter them, are shared international responsibilities that must be borne more equitably and predictably.',
 'In the Declaration, all 193 Member States of the United Nations reaffirmed the enduring importance of the international refugee protection regime, committed fully to respect the rights of refugees and migrants, pledged to provide more predictable and sustainable support to refugees and the communities that host them, and agreed to expand opportunities to achieve durable solutions for refugees.',
 '47 States committed to legal or policy changes to humanitarian aid; and expand access to third-country solutions.',
 'In order to give life to these commitments, the New York Declaration also sets out the key elements of a comprehensive refugee response and lays the groundwork for the adoption of a global compact on refugees in late 2018, both of which are explained in greater detail below.',
 '3.',
 'What is new in it?',
 'Among the key new elements are commitments by States to:   Strengthen and facilitate emergency responses to refugee movements and a smooth transition to sustainable approaches that invest in the resilience of both refugees and the communities that host them;  Provide additional and predictable humanitarian funding and development support to host countries;  Explore additional avenues for refugees to be admitted to third countries, including through increased resettlement; and  Support the development and application of a comprehensive refugee response framework (CRRF) for large refugee movements, applicable to both protracted and new situations.',
 '3    THE NEW YORK DECLARATION FAQs 4.',
 'Does it cover all those forced to flee their countries?',
 'The New York Declaration addresses large movements of refugees and migrants.',
 'It covers all refugees.',
 'A refugee is understood in international law to be a person who is outside his or her country of origin and who cannot return due to a well-founded fear of persecution for reasons of race, religion, nationality, membership of a particular social group or political opinion.',
 'The person is in need of international protection when his or her country of origin is unable or unwilling to provide protection against the harm feared.',
 'This definition is at the heart of the 1951 Refugee Convention and its 1967 Protocol and is also reflected in regional instruments.',
 'It has broad and enduring scope.',
 'It encompasses those who flee individual persecution, as well as those fleeing armed conflict or violence associated with one or more of the above-noted grounds.',
 'It includes those fleeing State and non-State actors and has been the basis for providing protection, amongst others, for those escaping war, conflict, human rights abuses, gang violence, domestic abuse and other forms of harm.',
 'There may also be persons who are forced to flee or are displaced across borders in the context of sudden- or slow-onset disasters, or in the context of the effects of climate change, who are not refugees.',
 'This group is also covered by the New York Declaration.',
 '5.',
 'Are vulnerable migrants in the same situation as refugees?',
 'There are some situations where migrants and refugees face similar risks.',
 'These include:   Exploitation or abuse by smugglers/traffickers or unscrupulous employers; and,  Risk of harm due to personal circumstances.',
 'People in this category could include, for example, unaccompanied or separated children, women at risk, elderly people, persons with disabilities or medical needs, or survivors of torture or trauma.',
 'While refugees often share the same vulnerabilities as migrants when they travel in similar conditions and along the same routes, it is important to bear in mind that refugees have an additional vulnerability that migrants do not, namely the well-founded fear of persecution that makes them a refugee.',
 'They are unable to avail themselves of the protection of the State that they have fled, which is why the international community has long recognized the additional duties owed to refugees, as enshrined in the 1951 Refugees Convention, its 1967 Protocol, regional instruments, and the corresponding rules of customary international law.',
 'Comprehensive Refugee Response Framework 6.',
 'What is it?',
 'The New York Declaration sets out the key elements of a comprehensive refugee response framework which are presented in the paragraph below.',
 'In the Declaration, UN Member States request UNHCR to engage with States and all relevant stakeholders to apply the comprehensive framework, and to further develop situation involving large movements of refugees.',
 'The framework presents a comprehensive response designed to ensure a) rapid and well-supported reception and admission measures; b) support for immediate and ongoing needs (, protection, health, education); c) assistance to national/local institutions and communities receiving refugees; and, d) expanded opportunities for durable solutions.',
 'These elements are designed to meet four objectives: to ease pressures on countries that host large numbers of refugees, to enhance refugee self-reliance, to expand third-country solutions, and to support conditions in countries of origin for return in safety and dignity.',
 '4    THE NEW YORK DECLARATION FAQs The elements of the CRRF elaborated in the New York Declaration draw on best practices from over 65 years of experience in international refugee protection, humanitarian assistance and the search for solutions.',
 'The elements, while comprehensive, are not necessarily exhaustive.',
 '7.',
 'How is the CRRF different from current approaches to refugee responses?',
 'Rather than responding to refugee displacement through a purely, and often underfunded, humanitarian lens, the elements of the CRRF are designed to provide a more systematic and sustainable response that benefits both refugees and the communities that host them.',
 'It engages a much broader group of stakeholders: government at national and local levels, international and regional financial institutions, UN Agencies and NGO partners, refugees themselves, the private sector, and civil society actors.',
 'It seeks to ensure more sustainable responses by linking humanitarian and development efforts early on in a crisis, and by strengthening and making more inclusive service delivery, including through investment in national and local systems wherever possible.',
 'It also calls for more robust and expanded planning and opportunities for durable solutions.',
 'The New York Declaration envisages that in future, this framework will be applied to emergency and protracted refugee situations in a systematic and predictable way.',
 '8.',
 'How will the CRRF be applied?',
 'UNHCR has begun working with Member States and its international, national, local and partners to implement the comprehensive refugee response framework in a range of specific refugee situations.',
 'These will be selected on the basis of a number of relevant factors, including agreement and active engagement of the hosting State; potential for progress; availability of diverse and representative partners; regional diversity; and representation of different operational contexts (emergency, established and protracted situations).',
 'To date, a dozen countriesthose of Belize, Djibouti, Costa Rica, Ethiopia, Guatemala, Honduras, Kenya, Mexico, Panama, the Somalia situation- which includes Somalia and  neighbouring countries hosting Somali refugees, Uganda and Zambia have begun applying the CRRF.',
 'UNHCR continues to explore opportunities with Member States from other regions to ensure geographical diversity.',
 'Further consultations will be conducted to apply the comprehensive refugee response framework to new emergency situations and contexts beyond the specific roll-out.',
 'UNHCR has worked with partners to draw lessons from the application of existing models that deliver holistic responses to refugee crises, such as the Regional Refugee & Resilience Plan (3RP) in response to the Syria crisis.',
 'For more information on the CRRF, please visit the CRRF global digital portal: http://crrf.unhcr.org/en/.',
 'Global Compact on Refugees 9.',
 'What is it?',
 'In addition to setting out the CRRF and requesting that the High Commissioner for Refugees commence its practical application, the New York Declaration calls on the High Commissioner to propose a global compact on refugees in his annual report to the United Nations General Assembly in 2018.',
 'The essential idea of the compact is to improve the way in which the international community responds to large movements of refugees and protracted refugee situations, most notably by providing for more equitable and predictable burden- and responsibility-sharing in support of countries and communities particularly affected.',
 'The global compact on refugees will consist of the CRRF, as agreed to by Member States in Annex I of the New York Declaration, and a programme of action that underpins the CRRF and facilitates its application.',
 'The programme of action builds on the wealth of good practices and experiences of  5    THE NEW YORK DECLARATION FAQs relevant stakeholders that were collected during extensive consultations.',
 'Five thematic discussions and the  in 2017 provided a forum for States and other stakeholders to put forward and consider concrete suggestions for the programme of action.',
 'The zero draft of the compact was issued in January 2018 ahead of six formal consultations with Member States aimed at ensuring that the report can be adopted by consensus.',
 'For further information on these elements, and the process that will be used to develop and consult on the global compact on refugees, see http://www.unhcr.org/refugeecompact .',
 '10.',
 'Will it be legally binding?',
 'The compact will not be legally binding.',
 'But, if adopted, it will be a powerful international agreement on how to respond better to large movements of refugees.',
 'Indeed, we already have a strong expression of political will in the New York Declaration.',
 'The compact will operationalize this by setting out the concrete measures and steps to be taken by governments and others.',
 'It will provide a blueprint, guiding the response to ensure host communities get the timely support they need, that refugees are better included in host communities (with access to health, education, livelihoods) and can rebuild their lives, and that solutions to the plight of refugees are sought from the start.',
 '11.',
 'How does it interact with the 1951 Refugee Convention?',
 'The normative legal regime for refugees is grounded in international law, notably the 1951 Convention relating to the Status of Refugees and its 1967 Protocol, as well as regional refugee instruments.',
 'The global compact on refugees will not create new legal norms or envision a fundamentally different international architecture for refugee protection.',
 'Rather, it provides the framework for applying these norms in large-scale influx, as well as protracted refugee situations, grounded in the principles of international cooperation and responsibility-sharing.',
 'Global compact for safe, orderly and regular migration 12.',
 'What is it?',
 'In addition to the global compact on refugees, the New York Declaration also provides for the adoption in 2018 of a global compact for safe, orderly and regular migration.',
 'It is envisaged that the global compact on safe, orderly and regular migration willin the words of the New York Declarationout a range of principles, commitments and understandings among Member States regarding   This is a separate compact that is being developed through a process of intergovernmental negotiation that is being co-facilitated by the Permanent Representatives of Switzerland and Mexico in New York.',
 'The input on the United Nations system is being coordinated by the Special Representative of the Secretary-General for International Migration, Ms Louise Arbour.',
 '13.',
 'How is the migration compact different from the global compact on refugees?',
 'The global compact on refugees will draw on lessons learned from the application of the CRRF and be proposed by UNHCR following consultations with Member States and other relevant stakeholders.',
 'In contrast, the global compact for safe, orderly and regular migration will articulate, for the first time, a  6    THE NEW YORK DECLARATION FAQs comprehensive framework for migration and be developed through a Member State driven process.',
 'The first draft of the GCM was released on the 5 February 2018 and can be accessed here.',
 '14.',
 'Wposition in regard to the global compact on safe, orderly and regular migration?',
 'UNHCR strongly supports the migration compact process and believes that the successful adoption of each compact will help to reinforce the objectives of the other.',
 'In particular, UNHCR hopes that the migration compact can achieve:  Enhanced international migration governance;  New and expanded channels for safe and regular migration;   Promoting respect for the human rights of migrants;   Protection of migrants in transit; and,   Protection of migrants in countries in crisis.',
 'UNHCR is taking part in the discussions for the migration compact, including to ensure both compacts complement each other on issues relevant to both, such as addressing xenophobia and intolerance, trafficking and smuggling, rescue at sea, and data collection and analysis.',
 '15.',
 'What is Urelation to the global compact on safe, orderly and regular migration?',
 'In the New York Declaration, Member States ask UNHCR to contribute its expertise to the development of the global compact for safe, orderly and regular migration, as well as to the elaboration of non-binding principles for migrants in vulnerable situations.',
 'For many years, UNHCR has worked with migration partners and provided guidance to States on how best to respond to mixed flows of refugees and migrants, and to initiatives for the protection of migrants in countries in crisis and those displaced by climate change and disasters.',
 'Areas where UNHCR expects to contribute to the global compact for safe, orderly and regular migration include:   Ensuring coherence and complementarity between the two compacts, especially on cross-cutting issues such as trafficking/smuggling, rescue at sea and promoting tolerance;   Addressing the needs of migrants in vulnerable situations; and  Expanding possibilities for increased safe migration opportunities, which could also benefit refugees (, family reunification, labour mobility).',
 'Relationship between the two global compacts 16.',
 'What is a global compact?',
 'The term compact refers to an agreement that is not legally binding but that captures, by consensus, both political and concrete actions of Member States and others relevant stakeholders to improve the way the international community responds to displacement.',
 '17.',
 'Why are there two compacts?',
 'The New York Declaration specifically provides for two compacts.',
 'This is in recognition of the fact that, for refugees, there is a specific legal regime already in place, and a framework that is elaborated in the New York Declaration for addressing large refugee movements.',
 'The New York Declaration also sets out the objectives for this framework, which are to: ease pressures on host countries; enhance refugee self-reliance; expand access to third country solutions; and, support conditions in country of origin for return in safety and dignity.',
 '7    THE NEW YORK DECLARATION FAQs  In contrast, there is no specialized comprehensive legal regime concerning migrants, and no agreed framework for addressing large movements of migrants.',
 'So, the starting point for achieving greater predictability and responsibility sharing for refugees is different than for enhancing the global governance of migration.',
 'In regard to migrants, the New York Declaration provides for the development of a global compact for safe, orderly and regular migration that will set out a range of principles, commitments and understandings regarding all aspects of international migration.',
 'The New York Declaration sets out a non-exhaustive list of twenty four issues  including the international governance of migration, remittances and their contribution to development, and combating trafficking in persons - that could be included in a global compact, reflecting the broad scope of issues that could possibly be addressed.',
 '18.',
 'How will the two compacts relate to one another?',
 'The United Nations General Assembly has described the processes leading to the two global compacts two compacts:   The global compact on refugees is intended to support a more comprehensive and predictable response to large-scale movements of refugees, including in protracted situations, by building upon the comprehensive refugee response framework and the wider international protection regime.',
 'It will aim to better protect and assist refugees and others in need of international protection to provide more adequate and predictable support to hosting countries and communities.',
 'The New York Declaration envisages a much wider scope for the global compact on safe, orderly and regular migration, on the other hand.',
 'It proposed that the migration compact  envisages -exhaustive list of 24 possible topics that the migration compact could address.',
 'Despite their different natures, however, there are areas in which there will be overlap between the two global compacts.',
 'These could include providing for adequate reception and determination of specific needs, efforts to reduce stigmatization, and combating sexual exploitation and abuse.',
 'UNHCR does not believe that all of these overlapping topics need to be dealt with in precisely the same way in each compact.',
 'Each compact has its own purpose and process.',
 'The areas of overlap should be addressed in each respective compact in a rationale.',
 'For example, whilst international cooperation to combat trafficking might belong more naturally in the migration compact, the global compact on refugees could address, inter alia, the identification of victims of trafficking within large movements of refugees.',
 'That being said, the ways in which the areas of overlap are dealt with in each compact should be coordinated, complementary and mutually reinforcing.',
 'There are many issues affecting refugees and migrants that require a common international response, and many areas where treatment should not be dependent on status.',
 '8    THE NEW YORK DECLARATION FAQs UNHCR is committed to working with all relevant stakeholders to achieve this goal.'];